import type { Department, Employee, DashboardStats, User } from '@/types';

export const mockUsers: (User & { password: string })[] = [
  {
    id: 'usr-1',
    name: 'Nguyễn Văn Quản Trị',
    email: 'admin@hrm.vn',
    password: 'password123',
    role: 'admin',
    department: 'Ban Giám Đốc',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-2',
    name: 'Trần Thị Nhân Sự',
    email: 'hr@hrm.vn',
    password: 'password123',
    role: 'hr_manager',
    department: 'Phòng Nhân Sự',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Phòng Công Nghệ Thông Tin (IT)',
    code: 'IT',
    managerName: 'Lê Minh Tuấn',
    employeeCount: 14,
    description: 'Phát triển phần mềm, hạ tầng hệ thống và bảo mật thông tin.',
  },
  {
    id: 'dept-2',
    name: 'Phòng Nhân Sự & Đào Tạo',
    code: 'HR',
    managerName: 'Trần Thị Nhân Sự',
    employeeCount: 6,
    description: 'Tuyển dụng, đào tạo, quản lý hồ sơ và phúc lợi nhân viên.',
  },
  {
    id: 'dept-3',
    name: 'Phòng Kinh Doanh & Marketing',
    code: 'SALES_MKT',
    managerName: 'Hoàng Quốc Việt',
    employeeCount: 18,
    description: 'Tìm kiếm khách hàng, xúc tiến bán hàng và truyền thông thương hiệu.',
  },
  {
    id: 'dept-4',
    name: 'Phòng Tài Chính - Kế Toán',
    code: 'ACC',
    managerName: 'Phạm Hồng Nhung',
    employeeCount: 5,
    description: 'Quản lý thu chi, ngân sách, báo cáo tài chính và bảng lương.',
  },
  {
    id: 'dept-5',
    name: 'Phòng Vận Hành & CSKH',
    code: 'OPS',
    managerName: 'Đặng Ngọc Sơn',
    employeeCount: 9,
    description: 'Chăm sóc khách hàng, hỗ trợ dịch vụ và tối ưu quy trình nội bộ.',
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    code: 'EMP-001',
    fullName: 'Lê Minh Tuấn',
    email: 'tuan.lm@hrm.vn',
    phone: '0912 345 678',
    departmentId: 'dept-1',
    departmentName: 'Phòng Công Nghệ Thông Tin (IT)',
    position: 'Tech Lead / Trưởng nhóm kỹ thuật',
    status: 'active',
    salary: 45000000,
    joinDate: '2022-03-15',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    address: 'Cầu Giấy, Hà Nội',
  },
  {
    id: 'emp-002',
    code: 'EMP-002',
    fullName: 'Trần Thị Thu Hà',
    email: 'ha.ttt@hrm.vn',
    phone: '0988 123 456',
    departmentId: 'dept-2',
    departmentName: 'Phòng Nhân Sự & Đào Tạo',
    position: 'Chuyên viên Tuyển dụng Cao cấp',
    status: 'active',
    salary: 22000000,
    joinDate: '2023-01-10',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    address: 'Ba Đình, Hà Nội',
  },
  {
    id: 'emp-003',
    code: 'EMP-003',
    fullName: 'Hoàng Quốc Việt',
    email: 'viet.hq@hrm.vn',
    phone: '0977 456 789',
    departmentId: 'dept-3',
    departmentName: 'Phòng Kinh Doanh & Marketing',
    position: 'Trưởng phòng Kinh doanh',
    status: 'active',
    salary: 38000000,
    joinDate: '2021-08-01',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    address: 'Đống Đa, Hà Nội',
  },
  {
    id: 'emp-004',
    code: 'EMP-004',
    fullName: 'Phạm Hồng Nhung',
    email: 'nhung.ph@hrm.vn',
    phone: '0934 567 890',
    departmentId: 'dept-4',
    departmentName: 'Phòng Tài Chính - Kế Toán',
    position: 'Kế toán trưởng',
    status: 'active',
    salary: 32000000,
    joinDate: '2020-05-20',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    address: 'Thanh Xuân, Hà Nội',
  },
  {
    id: 'emp-005',
    code: 'EMP-005',
    fullName: 'Vũ Đức Thành',
    email: 'thanh.vd@hrm.vn',
    phone: '0965 234 567',
    departmentId: 'dept-1',
    departmentName: 'Phòng Công Nghệ Thông Tin (IT)',
    position: 'Senior Frontend Developer',
    status: 'active',
    salary: 30000000,
    joinDate: '2023-06-01',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    address: 'Nam Từ Liêm, Hà Nội',
  },
  {
    id: 'emp-006',
    code: 'EMP-006',
    fullName: 'Ngô Mỹ Linh',
    email: 'linh.nm@hrm.vn',
    phone: '0943 890 123',
    departmentId: 'dept-3',
    departmentName: 'Phòng Kinh Doanh & Marketing',
    position: 'Marketing Executive',
    status: 'probation',
    salary: 16000000,
    joinDate: '2026-08-01',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    address: 'Hai Bà Trưng, Hà Nội',
  },
  {
    id: 'emp-007',
    code: 'EMP-007',
    fullName: 'Đỗ Hải Đăng',
    email: 'dang.dh@hrm.vn',
    phone: '0922 678 901',
    departmentId: 'dept-1',
    departmentName: 'Phòng Công Nghệ Thông Tin (IT)',
    position: 'Backend Developer',
    status: 'probation',
    salary: 20000000,
    joinDate: '2026-07-15',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    address: 'Hoàng Mai, Hà Nội',
  },
  {
    id: 'emp-008',
    code: 'EMP-008',
    fullName: 'Nguyễn Bích Phương',
    email: 'phuong.nb@hrm.vn',
    phone: '0911 223 344',
    departmentId: 'dept-5',
    departmentName: 'Phòng Vận Hành & CSKH',
    position: 'Customer Support Lead',
    status: 'active',
    salary: 19000000,
    joinDate: '2022-11-01',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    address: 'Tây Hồ, Hà Nội',
  },
  {
    id: 'emp-009',
    code: 'EMP-009',
    fullName: 'Bùi Anh Tuấn',
    email: 'tuan.ba@hrm.vn',
    phone: '0909 888 777',
    departmentId: 'dept-1',
    departmentName: 'Phòng Công Nghệ Thông Tin (IT)',
    position: 'UI/UX Designer',
    status: 'on_leave',
    salary: 25000000,
    joinDate: '2024-02-15',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    address: 'Hà Đông, Hà Nội',
  },
  {
    id: 'emp-010',
    code: 'EMP-010',
    fullName: 'Đinh Thị Mai',
    email: 'mai.dt@hrm.vn',
    phone: '0978 111 222',
    departmentId: 'dept-4',
    departmentName: 'Phòng Tài Chính - Kế Toán',
    position: 'Kế toán viên',
    status: 'resigned',
    salary: 15000000,
    joinDate: '2021-04-01',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    address: 'Long Biên, Hà Nội',
  },
];

export const getMockDashboardStats = (): DashboardStats => {
  const activeCount = mockEmployees.filter((e) => e.status === 'active' || e.status === 'probation').length;
  return {
    totalEmployees: mockEmployees.length,
    activeEmployees: activeCount,
    totalDepartments: mockDepartments.length,
    attendanceToday: Math.round(activeCount * 0.94),
    attendanceRate: 94.2,
    turnoverRate: 2.1,
    departmentDistribution: mockDepartments.map((dept) => ({
      name: dept.name.split(' (')[0],
      value: mockEmployees.filter((e) => e.departmentId === dept.id).length,
    })),
    hiringTrend: [
      { month: 'T1', hires: 4, departures: 1 },
      { month: 'T2', hires: 3, departures: 0 },
      { month: 'T3', hires: 6, departures: 2 },
      { month: 'T4', hires: 5, departures: 1 },
      { month: 'T5', hires: 7, departures: 1 },
      { month: 'T6', hires: 8, departures: 2 },
      { month: 'T7', hires: 6, departures: 0 },
      { month: 'T8', hires: 9, departures: 1 },
    ],
    attendanceTrend: [
      { day: 'T2', present: 48, absent: 2, late: 2 },
      { day: 'T3', present: 50, absent: 1, late: 1 },
      { day: 'T4', present: 49, absent: 2, late: 1 },
      { day: 'T5', present: 51, absent: 0, late: 1 },
      { day: 'T6', present: 47, absent: 3, late: 2 },
    ],
  };
};
